frontend.app.uri: http://localhost:4200

########################
# Security
########################
spring.security.oauth2.resourceserver.opaquetoken:
  introspection-uri: http://localhost:8080/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: JwEIU0vtWtSVOQxsW46ZqBXNypYahQp7