frontend.app.uri: "http://host.docker.internal:4201"

eureka.client.serviceUrl:
  defaultZone: ${eureka.url}

########################
# Security
########################
spring.security.oauth2.resourceserver.opaquetoken:
  introspection-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: ${oauth.secret}