frontend.app.uri: "http://host.docker.internal:4201"

eureka.client.serviceUrl:
  defaultZone: ${eureka.url:http://host.docker.internal:8761/eureka/}

########################
# Security
########################
spring.security.oauth2.resourceserver.opaquetoken:
  introspection-uri: http://host.docker.internal:8080/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: DQaXG75c2bAqfHA3CXsboQek4xxF2Y6Y