server.port: 8082

########################
# Cloud stream
########################
spring.cloud.stream:
  bindings:
    matches-out-0:
      destination: sample-match-topic-3
    matches-in-0:
      destination: sample-match-topic-3

########################
# Security
########################
security.mode: true

spring.security.oauth2.resourceserver.opaqueToken:
  introspection-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: ${oauth.secret}

########################
# Logging
########################
logging.level:
  com.piter.match.api: DEBUG
  org.apache.kafka.clients: WARN