server.port: 8082

########################
# Cloud stream
########################
spring.cloud.stream:
  bindings:
    matches-out-0:
      destination: sample-match-topic-3
    matches-in-0:
      destination: sample-match-topic-3

########################
# Security
########################
security.mode: true

spring.security.oauth2.resourceserver.opaqueToken:
  introspection-uri: http://${keycloak.base.url:host.docker.internal}:8080/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: ${oauth.secret}

########################
# Logging
########################
logging.level:
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
  org.springframework.data.mongodb.repository.support: DEBUG
  org.springframework.cache: TRACE
  com.piter.match.api: DEBUG