version: 2.1

parameters:
  bet-api-modified:
    type: boolean
    default: false
  bet-event-aggregator-modified:
    type: boolean
    default: false
  match-api-modified:
    type: boolean
    default: false

jobs:
  shared-library-install:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/bet-microservices/shared-library
    steps:
      - checkout:
          path: ~/bet-microservices
      - run:
          name: Install
          command: mvn -B clean install
  bet-api-build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/bet-microservices/bet-api
    steps:
      - checkout:
          path: ~/bet-microservices
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  bet-event-aggregator-build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/bet-microservices/bet-event-aggregator
    steps:
      - checkout:
          path: ~/bet-microservices
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  match-api-build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/bet-microservices
    steps:
      - checkout:
          path: ~/bet-microservices
      - run:
          command: cd shared-library
      - run:
          name: Install shared library
          command: mvn -B clean install
      - run:
          command: cd ../match-api
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  bet-api:
    when: << pipeline.parameters.bet-api-modified >>
    jobs:
      - shared-library-install
      - bet-api-build-and-test:
          requires:
            - shared-library-install
  bet-event-aggregator:
    when: << pipeline.parameters.bet-event-aggregator-modified >>
    jobs:
      - shared-library-install
      - bet-event-aggregator-build-and-test:
          requires:
            - shared-library-install
  match-api:
    when: << pipeline.parameters.match-api-modified >>
    jobs:
      - shared-library-install
      - match-api-build-and-test:
          requires:
            - shared-library-install
