spring:
  main:
    web-application-type: REACTIVE
  data:
    mongodb:
      authentication-database: admin
  cloud.config.enabled: false

security.mode: false

########################
# Cloud stream
########################
spring.cloud.stream:
  bindings:
    matches-out-0:
      destination: match-topic
    matches-in-0:
      destination: match-topic

########################
# Logging
########################
logging.level:
  com.piter.match.api: DEBUG
  org.apache.kafka.clients: WARN