spring:
  application.name: match-api
  kafka.consumer.properties:
    spring.json.trusted.packages: "*"

eureka.client.serviceUrl:
  defaultZone: ${eureka.url:http://localhost:8761/eureka/}

########################
# Cloud stream
########################
spring.cloud.stream.kafka.bindings:
  matches-out-0:
    producer:
      configuration:
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
  matches-in-0:
    consumer:
      configuration:
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer

########################
# Kafka Match producer
########################
match.producer.binding: matches-out-0

cache:
  expiry-in-hours: 2

########################
# Actuator
########################
management:
  endpoints.web.exposure.include: health, info
  info:
    env.enabled: true
    build.enabled: true
    git:
      enabled: true
      mode: full

info.application:
  name: Match API
  description: Match API microservice for betting
  author.name: Piter

########################
# Swagger
########################
springdoc:
  swagger-ui.path: /swagger-doc/swagger-ui.html
  api-docs.path: /swagger-doc/v3/api-docs