spring:
  application.name: match-api
  data:
    mongodb:
      port: 27017
      host: localhost

logging.level:
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
  org.springframework.cache: TRACE