spring:
  main.web-application-type: REACTIVE
  data:
    mongodb:
      port: 0
      host: 127.0.0.1
  cloud.config.enabled: false

security.mode: true

de.flapdoodle.mongodb.embedded.version: 5.0.6

eureka.client.enabled: false