spring:
  application.name: match-api
  data:
    mongodb:
      port: 27017
      host: localhost

security.mode: false

########################
# Cloud stream
########################
spring.cloud.stream:
  kafka:
    binder:
      brokers: localhost:9092
    bindings:
      matches-out-0:
        producer:
          configuration:
            key.serializer: org.apache.kafka.common.serialization.LongSerializer
      matches-in-0:
        consumer:
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
  bindings:
    matches-out-0:
      destination: sample-match-topic-2
    matches-in-0:
      destination: sample-match-topic-2

########################
# Kafka Match producer
########################
match.producer.binding: matches-out-0

cache:
  expiry-in-hours: 2

########################
# Actuator
########################
management:
  endpoints.web.exposure.include: health, info
  info:
    env.enabled: true
    build.enabled: true
    git:
      enabled: true
      mode: full

info:
  application:
    name: Match API
    description: Match API microservice for betting
    author.name: Piter

########################
# Swagger
########################
springdoc:
  swagger-ui.path: /swagger-doc/swagger-ui.html
  api-docs.path: /swagger-doc/v3/api-docs

########################
# Logging
########################
logging.level:
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
  org.springframework.data.mongodb.repository.support: DEBUG
  org.springframework.cache: TRACE
  com.piter.match.api: DEBUG