########################
# OAuth2 Security
########################
spring.security.oauth2.client:
  registration.match-management:
    client-id: match-management-app
    client-secret: ${oauth.secret}
    authorization-grant-type: authorization_code
    scope: openid, roles
    redirect-uri: ${management.base.url}/login/oauth2/code/match-management
  provider.match-management:
    authorization-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/auth
    token-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/token
    jwk-set-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/certs
    user-info-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/userinfo
    user-name-attribute: preferred_username

########################
# Logging
########################
logging.level:
  com.piter.match.service: DEBUG