server.port: 8081

spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

mock.enabled: false

########################
# Cloud
########################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

cache:
  expiry-in-hours: 2