server.port: 8083
spring:
  data.mongodb:
    port: 27017
    host: localhost
    username: mongoUsername
    password: mongoPassword
    database: betLeague
    authentication-database: admin
  cloud.config.enabled: false

########################
# Cloud stream
########################
spring.cloud.stream:
  kafka.binder.brokers: localhost:29092
  bindings:
    bets-out-0:
      destination: sample-bet-request-topic-2
    bets-in-0:
      destination: sample-bet-topic

########################
# Security
########################
spring.security.oauth2.resourceserver.opaqueToken:
  introspection-uri: http://localhost:8080/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: JwEIU0vtWtSVOQxsW46ZqBXNypYahQp7

########################
# Logging
########################
logging.level:
  com.piter.bet.api: DEBUG
  org.apache.kafka.clients: WARN

