version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    container_name: keycloak-db
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    command: "start-dev"
    depends_on:
      - postgres
networks:
  keycloak-network:
    driver: bridge