version: "3.8"

volumes:
  postgres_data:
    driver: local
  zookeeper_log:
    driver: local
  zookeeper_data:
    driver: local
  broker_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgresUsername
      POSTGRES_PASSWORD: postgresPassword
    container_name: keycloak-db
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: "keycloak"
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: postgresUsername
      KC_DB_PASSWORD: postgresPassword
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    command: "start-dev"
    depends_on:
      - postgres
  mongodatabase:
    image: mongo:latest
    container_name: "mongodatabase"
    ports:
      - "27017:27017"
    networks:
      - keycloak-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUsername
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    volumes:
      - mongodb_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.10.arm64
    platform: linux/arm64
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - keycloak-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
  broker:
    image: confluentinc/cp-kafka:7.1.10.arm64
    platform: linux/arm64
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    networks:
      - keycloak-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: on-failure
    volumes:
      - broker_data:/var/lib/kafka/data