server.port: 8083

########################
# Cloud stream
########################
spring.cloud.stream:
  bindings:
    bets-out-0:
      destination: sample-bet-request-topic-2
    bets-in-0:
      destination: sample-bet-topic

########################
# Security
########################
spring.security.oauth2.resourceserver.opaqueToken:
  introspection-uri: ${keycloak.base.url}/realms/BetSpringBootKeycloak/protocol/openid-connect/token/introspect
  client-id: bet-login-app
  client-secret: ${oauth.secret}

########################
# Logging
########################
logging.level:
  com.piter.bet.api: DEBUG
  org.apache.kafka.clients: WARN

