spring.application.name: bet-event-aggregator

########################
# Cloud stream
########################
spring.cloud:
  function.definition: bets;matches
  stream.kafka.streams.binder:
    deserializationExceptionHandler: logAndContinue
    functions:
      bets.application-id: bets
      matches.application-id: matches
    configuration:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
      spring.json.trusted.packages: "*"
